-- MySQL Script generated by MySQL Workbench
-- qua 10 dez 2025 19:17:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controlefinanceiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlefinanceiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlefinanceiro` ;
USE `controlefinanceiro` ;

-- -----------------------------------------------------
-- Table `controlefinanceiro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlefinanceiro`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlefinanceiro`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlefinanceiro`.`objetivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` FLOAT NOT NULL,
  `data` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_despesas_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_despesas_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `controlefinanceiro`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlefinanceiro`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlefinanceiro`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` ENUM('despesas', 'receitas') NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `controlefinanceiro`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlefinanceiro`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlefinanceiro`.`movimentacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` FLOAT NOT NULL,
  `data` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receita_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_movimentacao_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_receita_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `controlefinanceiro`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `controlefinanceiro`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
